# Assignment 01 For Numpy

Submitted By Samiullah

Roll number: PIAIC122111

Batch 12

1. Import the numpy package under the name np

In [49]:
import numpy as np

-----------------------------------------------------------------------------------------

1. Create a null vector of size 10

In [50]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

-----------------------------------------------------------------------------------------

1. Create a vector with values ranging from 10 to 49

In [51]:
vector_1 = np.arange(10, 50)
vector_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

-----------------------------------------------------------------------------------------

1. Find the shape of previous array in question 3

In [52]:
vector_1.shape

(40,)

-----------------------------------------------------------------------------------------

1. Print the type of the previous array in question 3

In [53]:
type(vector_1)

numpy.ndarray

-----------------------------------------------------------------------------------------

1. Print the numpy version and the configuration

In [54]:
print (np.__version__) #prints version
print (np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


-----------------------------------------------------------------------------------------

1. Print the dimension of the array in question 3

In [55]:
vector_1.ndim

1

-----------------------------------------------------------------------------------------

1. Create a boolean array with all the True values

In [56]:
bool_array = np.array([1,3,4,5,6,7,8,9,7,6], dtype = bool)
bool_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

-----------------------------------------------------------------------------------------

1. Create a two dimensional array

In [57]:
array_2d = np.array([[1,2,3,4,5,6],[9,8,7,6,5,4]])
array_2d

array([[1, 2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5, 4]])

-----------------------------------------------------------------------------------------

1. Create a three dimensional array

In [58]:
array_3d = np.array([[[1,2,3,4],[4,3,2,1]],[[5,6,7,8],[8,7,6,5]]])
array_3d

array([[[1, 2, 3, 4],
        [4, 3, 2, 1]],

       [[5, 6, 7, 8],
        [8, 7, 6, 5]]])

-----------------------------------------------------------------------------------------

Difficulty Level Easy

1. Reverse a vector (first element becomes last)

In [59]:
vector_array = np.arange(0, 10)
print(vector_array)

reverse_vector = vector_array[::-1]
print(reverse_vector)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


-----------------------------------------------------------------------------------------

1. Create a null vector of size 10 but the fifth value which is 1

In [60]:
null_vector = np.zeros(10)
null_vector[4] = 1
print (null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


-----------------------------------------------------------------------------------------

1. Create a 3x3 identity matrix

In [61]:
identity_matrix = np.eye(3)
print (identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


-----------------------------------------------------------------------------------------

1. arr = np.array([1, 2, 3, 4, 5])

Convert the data type of the given array from int to float

In [62]:
arr = np.array([1,2,3,4,5], dtype=float)
print(arr)
print (arr.dtype)

[1. 2. 3. 4. 5.]
float64


-----

1. arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

Multiply arr1 with arr2

In [63]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print (arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


-----------------------------------------------------------------------------------------

1. arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

Make an array by comparing both the arrays provided above

In [65]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print (arr1 == arr2)

[[False False False]
 [False False False]]


-----------------------------------------------------------------------------------------

1. Extract all odd numbers from arr with values(0-9)

In [69]:
num_array = np.arange(10)
print (num_array)
print (num_array[num_array%2 != 0])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


-----------------------------------------------------------------------------------------

1. Replace all odd numbers to -1 from previous array

In [71]:
num_array[num_array%2 != 0] = -1
print (num_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


-----------------------------------------------------------------------------------------

1. arr = np.arange(10)

Replace the values of indexes 5,6,7 and 8 to 12

In [75]:
arr = np.arange(10)
print (arr)
arr[4] = arr[5] = arr[6] = arr[7] = 12
print (arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 12 12 12 12  8  9]


-------------------------------------------

1. Create a 2d array with 1 on the border and 0 inside

In [91]:
arr2d = np.zeros((10,10), dtype = int)
arr2d[:, 0:1] = arr2d[:, 9:10] = arr2d[0:1, :] = arr2d[9:10, :] = 1

print(arr2d)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


-----------------------------------------------------------------------------------------

1. Difficulty Level Medium

arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [73]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print (arr2d)
arr2d[1,1] = 12
print (arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


-----------------------------------------------------------------------------------------

1. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Convert all the values of 1st array to 64

In [74]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print (arr3d)
arr3d[0,0,0]=arr3d[0,0,1]=arr3d[0,0,2]=64
print (arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


-----------------------------------------------------------------------------------------

1. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [96]:
arr_2d = np.arange(0,9).reshape(3,3)
print (arr_2d)
print ("***********************************")
arr_1d = arr_2d[0]
print (arr_1d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
***********************************
[0 1 2]


-----------------------------------------------------------------------------------------

1. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [97]:
arr_2d = np.arange(0,9).reshape(3,3)
print (arr_2d)
print ("************************************")
arr_val = arr_2d[1,1]
print (arr_val)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
************************************
4


-----------------------------------------------------------------------------------------

1. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [98]:
arr_2d = np.arange(0,9).reshape(3,3)
print (arr_2d)
print ("************************************")
print (arr_2d[0:2, 2:3])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
************************************
[[2]
 [5]]


-----------------------------------------------------------------------------------------

1. Create a 10x10 array with random values and find the minimum and maximum values

In [124]:
arr = np.array(np.random.randn(10,10)*10, dtype=np.int32)
print (arr)
print ("********************************")
arr_min, arr_max = arr.min(), arr.max()
print("minimum num in array is ", arr_min)
print("maximum num in array is", arr_max)
#print ("mininum number in array is "arr_min)

[[ -8  -3   0  -1  -1  -9  -7   0   6  -5]
 [ -1   0   5  -2  -1  -9  -1  15  -7  -8]
 [  9  -2  14   2  -6   3 -18  -1   2   0]
 [ -2  -5  -5   4   0 -12 -14  -5   7  -3]
 [  9 -14  -2   8  -6   0  -3   6  -3   7]
 [ 11   1   8   9  -9 -10  -2  -3   1   1]
 [ 17  10  14  -3 -11   3  10  13  13  -1]
 [ -2   2  -8   2  15   8  13  -3  16  10]
 [ -1 -32   2  -2 -12   4  -9   7  14   0]
 [ -7  11   1  -8  10   5  -7 -24 -10   0]]
********************************
minimum num in array is  -32
maximum num in array is 17


-----------------------------------------------------------------------------------------

# 27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

1. Find the common items between a and b

In [132]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Common items are : ",np.intersect1d(a,b))

Common items are :  [2 4]


-----------------------------------------------------------------------------------------

1. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Find the positions where elements of a and b match

In [133]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


-----------------------------------------------------------------------------------------

1. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

Find all the values from array data where the values from array names are not equal to Will

In [141]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names != 'Will')]

array([[ 1.38975297,  0.08529278, -1.1380804 , -1.16850502],
       [-0.17302625,  2.19219891, -0.65993084,  0.18974677],
       [ 0.44576295,  1.1954789 ,  1.44514626, -0.68456428],
       [ 0.18864295, -2.2521334 ,  0.80965758, -0.11557596],
       [-0.6447459 , -1.51374394,  0.74692614,  0.47474219]])

-----------------------------------------------------------------------------------------

1. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

Find all the values from array data where the values from array names are not equal to Will and Joe

In [147]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[((names != 'Will') | (names != 'Joe'))]

array([[ 0.56640243,  0.09085753,  0.86091429,  1.50732646],
       [ 1.66949947,  0.68676194,  1.31561422, -0.06737927],
       [-0.48198158,  0.62100211, -1.25807742, -0.65275259],
       [ 0.37229788,  0.3597962 ,  0.31117486, -0.44621107],
       [-0.4275036 ,  1.02594037, -1.46627247,  0.07669985],
       [ 1.31558505, -1.49037045, -0.04390033,  2.05088584],
       [-0.07586573, -0.27756394, -0.4432534 ,  0.17132751]])

-----------------------------------------------------------------------------------------

1. Difficulty Level Hard

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [150]:
arr_2d = np.arange(15.0).reshape(5,3)
arr_2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

-----------------------------------------------------------------------------------------

1. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [152]:
arr = np.arange(16.0).reshape(2,2,4)
arr

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

-----------------------------------------------------------------------------------------

1. Swap axes of the array you created in Question 32

In [153]:
arr.T

array([[[ 0.,  8.],
        [ 4., 12.]],

       [[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]]])

-----------------------------------------------------------------------------------------

1. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [155]:
arr_sqrt = np.arange(10)
np.sqrt(arr_sqrt)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

-----------------------------------------------------------------------------------------

1. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [158]:
ar1 = np.random.randn(12)
ar2 = np.random.randn(12)
print(np.maximum(ar1, ar2))

[ 1.68192917  0.58934246  0.48737884  1.00258382  0.91126312  0.5329313
 -0.59874317 -1.38181748  1.33613653 -0.67636381  0.77439946  1.17714953]


-----------------------------------------------------------------------------------------

1. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

Find the unique names and sort them out!

In [161]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

-----------------------------------------------------------------------------------------

1. a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])

From array a remove all items present in array b

In [164]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a,b)
print(a)

[1 2 3 4]


-----------------------------------------------------------------------------------------

1. Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [171]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[:, 1:2] = 10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

-----------------------------------------------------------------------------------------

1. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])

Find the dot product of the above two matrix

In [175]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
print (z)

[[ 28.  64.]
 [ 67. 181.]]


-----------------------------------------------------------------------------------------

1. Generate a matrix of 20 random values and find its cumulative sum

In [176]:
arr = np.random.randn(20)
cum_arr = np.cumsum(arr)
cum_arr

array([-0.58037558, -2.70860094, -3.08685428, -3.88854128, -4.34874309,
       -3.91175086, -3.00916746, -3.58177891, -2.48498576, -1.12960936,
       -1.01078002, -1.23311215,  0.06408611, -1.50151833, -1.77770542,
       -0.02783095,  1.5029134 , -0.61109032,  0.19649897, -0.42439895])

-----------------------------------------------------------------------------------------