# Numpy_Assignment_2::
Submitted By Samiullah

Roll number: PIAIC122111

Batch 12


# Question:1

Convert a 1D array to a 2D array with 2 rows?

Desired output::

array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

In [33]:
arr_1d = np.arange(10)
print (arr_1d)
print ("***********************")
arr_2d = arr_1d.reshape(2, 5)
print (arr_2d)

[0 1 2 3 4 5 6 7 8 9]
***********************
[[0 1 2 3 4]
 [5 6 7 8 9]]


# Question:2

How to stack two arrays vertically?

Desired Output::

        array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [34]:
arr1 = np.arange(10).reshape(2,5)
print (arr1)
arr2 = np.ones(10, int).reshape(2,5)
print (arr2)
print ("***************************")
print (np.vstack((arr1, arr2)))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
***************************
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# Question:3

How to stack two arrays horizontally?

Desired Output::

        array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [32]:
arr1 = np.arange(10).reshape(2,5)
print (arr1)
arr2 = np.ones(10, int).reshape(2,5)
print (arr2)
print ("***************************")
print (np.hstack((arr1, arr2)))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
***************************
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


# Question:4

How to convert an array of arrays into a flat 1d array?

Desired Output::

        array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr2d = np.arange(10).reshape(2,5)
print(arr2d)
print ("**************************")
arr1d = arr2d.flatten()
print (arr1d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
**************************
[0 1 2 3 4 5 6 7 8 9]


# Question:5

How to Convert higher dimension into one dimension?

Desired Output::

        array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [51]:
arr = np.arange(15).reshape(3,5)
print (arr)
print ("********************")
arr1d = arr.flatten()
print (arr1d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
********************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Question:6

Convert one dimension to higher dimension?

Desired Output::

        array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])

In [52]:
arr1d = np.arange(15)
print (arr1d)
print ("**************************")
arr2d = arr1d.reshape(5,3)
print (arr2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
**************************
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# Question:7

Create 5x5 an array and find the square of an array?

In [57]:
arr = np.arange(25).reshape(5,5)
print (arr)
print ("****************************")
sq_arr = np.square(arr)
print (sq_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
****************************
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


# Question:8

Create 5x6 an array and find the mean?

In [59]:
arr = np.arange(30).reshape(5,6)
print (arr)
print ("****************************")
mn_arr = np.mean(arr)
print ("mean of array is ", mn_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
****************************
mean of array is  14.5


# Question:9

Find the standard deviation of the previous array in Q8?¶

In [61]:
sd_arr = np.std(arr)
print ("standard deviation of array is ", sd_arr)

mean of array is  8.65544144839919


# Question:10

Find the median of the previous array in Q8?

In [62]:
md_arr = np.median(arr)
print ("median of array is ", md_arr)

median of array is  14.5


# Question:11

Find the transpose of the previous array in Q8?

In [65]:
print (arr)
print ("*******************************")
arr_t = arr.T
print ("Transpose of array is \n", arr_t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
*******************************
Transpose of array is 
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


# Question:12

Create a 4x4 an array and find the sum of diagonal elements?

In [93]:
arr = np.arange(1,17).reshape(4,4)
print (arr)
print ("****************************")
sum_diag = np.trace(arr)
print ("summ of Diagonal is ", sum_diag)
print ("and diagonal is ", np.diagonal(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
****************************
summ of Diagonal is  34
and diagonal is  [ 1  6 11 16]


# Question:13

Find the determinant of the previous array in Q12?

In [94]:
from numpy.linalg import det
det_arr = det(arr)
print ("Determinant of array is ", det_arr)

Determinant of array is  0.0


# Question:14

Find the 5th and 95th percentile of an array?

In [97]:
a = np.arange(1,50)
print(a)
print()
print("{0} - is the 5th percentile".format(round(np.percentile(a,5),2)))
print("{0} - is the 95th percentile".format(round(np.percentile(a,95),2)))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]

3.4 - is the 5th percentile
46.6 - is the 95th percentile


# Question:16

How to find if a given array has any null values?

In [101]:
a = np.arange(5)
print(a)
print(np.isnan(a).any())

print()
b = np.array([40,np.nan,50])
print(b)
print(np.isnan(b).any())

[0 1 2 3 4]
False

[40. nan 50.]
True
